[build-system]
requires = ["setuptools>=67.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "langextract"
version = "1.0.0"
description = "LangExtract: A library for extracting structured data from language models"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
authors = [
    {name = "Jing Wang", email = "jingwang.physics@gmail.com"}
]
dependencies = [
    "absl-py>=1.0.0",
    "aiohttp>=3.8.0",
    "anthropic>=0.60.0",
    "async_timeout>=4.0.0",
    "exceptiongroup>=1.1.0",
    "google-genai>=0.1.0",
    "ipykernel>=6.30.0",
    "libmagic>=1.0",
    "ml-collections>=0.1.0",
    "more-itertools>=8.0.0",
    "numpy>=1.20.0",
    "openai>=0.27.0",
    "pandas>=1.3.0",
    "pydantic>=1.8.0",
    "python-dotenv>=0.19.0",
    "python-magic>=0.4.27",
    "requests>=2.25.0",
    "tqdm>=4.64.0",
    "typing-extensions>=4.0.0",
]

[project.urls]
"Homepage" = "https://github.com/google/langextract"
"Repository" = "https://github.com/google/langextract"
"Documentation" = "https://github.com/google/langextract/blob/main/README.md"
"Bug Tracker" = "https://github.com/google/langextract/issues"

[project.optional-dependencies]
dev = [
    "black>=23.7.0",
    "pylint>=2.17.5",
    "pytest>=7.4.0",
    "pytype>=2024.10.11",
    "tox>=4.0.0",
]
test = [
    "pytest>=7.4.0",
    "tomli>=2.0.0"
]

[tool.setuptools]
packages = ["langextract"]
include-package-data = false

[tool.setuptools.exclude-package-data]
"*" = [
    "docs*",
    "tests*",
    "kokoro*",
    "*.gif",
    "*.svg",
]

[tool.pytest]
testpaths = ["tests"]
python_files = "*_test.py" 

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
